sudo: false
language: ruby

before_install: gem update bundler

rvm:
  - 2.6.0
  - 2.5.3

gemfile:
  - gemfiles/rails_52.gemfile
  - gemfiles/rails_51.gemfile
  - gemfiles/rails_50.gemfile
  - gemfiles/rails_42.gemfile
